"""autogenerated by genpy from auv_msgs/MotorCommands.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MotorCommands(genpy.Message):
  _md5sum = "ea2d5f40a47b1880926c752b1d9424bf"
  _type = "auv_msgs/MotorCommands"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 cmd_surge_starboard
int32 cmd_surge_port
int32 cmd_sway_bow
int32 cmd_sway_stern
int32 cmd_heave_bow
int32 cmd_heave_stern
"""
  __slots__ = ['cmd_surge_starboard','cmd_surge_port','cmd_sway_bow','cmd_sway_stern','cmd_heave_bow','cmd_heave_stern']
  _slot_types = ['int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cmd_surge_starboard,cmd_surge_port,cmd_sway_bow,cmd_sway_stern,cmd_heave_bow,cmd_heave_stern

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotorCommands, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.cmd_surge_starboard is None:
        self.cmd_surge_starboard = 0
      if self.cmd_surge_port is None:
        self.cmd_surge_port = 0
      if self.cmd_sway_bow is None:
        self.cmd_sway_bow = 0
      if self.cmd_sway_stern is None:
        self.cmd_sway_stern = 0
      if self.cmd_heave_bow is None:
        self.cmd_heave_bow = 0
      if self.cmd_heave_stern is None:
        self.cmd_heave_stern = 0
    else:
      self.cmd_surge_starboard = 0
      self.cmd_surge_port = 0
      self.cmd_sway_bow = 0
      self.cmd_sway_stern = 0
      self.cmd_heave_bow = 0
      self.cmd_heave_stern = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6i.pack(_x.cmd_surge_starboard, _x.cmd_surge_port, _x.cmd_sway_bow, _x.cmd_sway_stern, _x.cmd_heave_bow, _x.cmd_heave_stern))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.cmd_surge_starboard, _x.cmd_surge_port, _x.cmd_sway_bow, _x.cmd_sway_stern, _x.cmd_heave_bow, _x.cmd_heave_stern,) = _struct_6i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6i.pack(_x.cmd_surge_starboard, _x.cmd_surge_port, _x.cmd_sway_bow, _x.cmd_sway_stern, _x.cmd_heave_bow, _x.cmd_heave_stern))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.cmd_surge_starboard, _x.cmd_surge_port, _x.cmd_sway_bow, _x.cmd_sway_stern, _x.cmd_heave_bow, _x.cmd_heave_stern,) = _struct_6i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6i = struct.Struct("<6i")
