"""autogenerated by genpy from auv_msgs/Solenoid.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Solenoid(genpy.Message):
  _md5sum = "0efcb9185f05bca53eb2775d2b56d3f1"
  _type = "auv_msgs/Solenoid"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool solenoid1
bool solenoid2
bool solenoid3
bool solenoid4
bool solenoid5
bool solenoid6

"""
  __slots__ = ['solenoid1','solenoid2','solenoid3','solenoid4','solenoid5','solenoid6']
  _slot_types = ['bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       solenoid1,solenoid2,solenoid3,solenoid4,solenoid5,solenoid6

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Solenoid, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.solenoid1 is None:
        self.solenoid1 = False
      if self.solenoid2 is None:
        self.solenoid2 = False
      if self.solenoid3 is None:
        self.solenoid3 = False
      if self.solenoid4 is None:
        self.solenoid4 = False
      if self.solenoid5 is None:
        self.solenoid5 = False
      if self.solenoid6 is None:
        self.solenoid6 = False
    else:
      self.solenoid1 = False
      self.solenoid2 = False
      self.solenoid3 = False
      self.solenoid4 = False
      self.solenoid5 = False
      self.solenoid6 = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6B.pack(_x.solenoid1, _x.solenoid2, _x.solenoid3, _x.solenoid4, _x.solenoid5, _x.solenoid6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.solenoid1, _x.solenoid2, _x.solenoid3, _x.solenoid4, _x.solenoid5, _x.solenoid6,) = _struct_6B.unpack(str[start:end])
      self.solenoid1 = bool(self.solenoid1)
      self.solenoid2 = bool(self.solenoid2)
      self.solenoid3 = bool(self.solenoid3)
      self.solenoid4 = bool(self.solenoid4)
      self.solenoid5 = bool(self.solenoid5)
      self.solenoid6 = bool(self.solenoid6)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6B.pack(_x.solenoid1, _x.solenoid2, _x.solenoid3, _x.solenoid4, _x.solenoid5, _x.solenoid6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.solenoid1, _x.solenoid2, _x.solenoid3, _x.solenoid4, _x.solenoid5, _x.solenoid6,) = _struct_6B.unpack(str[start:end])
      self.solenoid1 = bool(self.solenoid1)
      self.solenoid2 = bool(self.solenoid2)
      self.solenoid3 = bool(self.solenoid3)
      self.solenoid4 = bool(self.solenoid4)
      self.solenoid5 = bool(self.solenoid5)
      self.solenoid6 = bool(self.solenoid6)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6B = struct.Struct("<6B")
