hydrophones:
    audio:
        buffersize: 1024
        freq: 192000
    env:
        is_practice: False
        is_simulation: False
        speed: 1500.00
    mic:
        "0":
            x: 0.00
            y: 0.00
        "1":
            x: 0.01
            y: 0.00
        "2":
            x: 0.01
            y: 0.01
        "3":
            x: 0.00
            y: 0.01
    pinger:
        length: 0.004
        period: 2.00
        competition:
            delay: 0.00
            freq: 30000
        practice:
            delay: 0.90
            freq: 35000
