pause: 3
countdown: 5
speed: 5
stop_time: 5

# practice side
#dropper_index: 1
#torp_yaw: 1.57
#yaws: [0, 0.048, 1.037]
#times: [62.84, 30.08, 97.0]
#depths: [1.7, 1.81, 1.812]
#
# competition side
#dropper_index: 1
#torp_yaw: 0.5
#yaws: [0, -0.1, -0.72]
#times: [65.84, 29.4, 96.0]
#depths: [1.7, 1.81, 1.812]
#
#Kiddy Pool
dropper_index: -1
torp_yaw: 0.0
yaws: []
times: []
depths: []
