#! /usr/bin/env python2.7

import cv2
from cv_backbone import CvBackbone
import numpy as np

cb = CvBackbone.CvBackbone('channels')

def channels(img):
    b, g, r = cv2.split(img) # Possibly wrong order?
    cb.publishImages((r,g,b), 'rgb')
    h, s, v = cv2.split(cv2.cvtColor(img, cv2.COLOR_BGR2HSV))
    cb.publishImages((h,s,v), 'hsv')
    l, a, b = cv2.split(cv2.cvtColor(img, cv2.COLOR_BGR2LAB))
    cb.publishImages((l,a,b), 'lab')
    normalized = np.uint8(np.right_shift(cv2.normalize(h.astype(np.uint16)*s.astype(np.uint16)), 8))
    multiplied =np.uint8(np.right_shift(np.uint16(h)*np.uint16(s), 8))
    cb.publishImage(multiplied, 'hs')
    added = np.uint8((np.uint16(r)+np.uint16(g))/2)
    cb.publishImage(added,'r_plus_g')
    subbed = np.uint8((2**8 + (np.int16(r) - np.int16(g)))/2)
    cb.publishImage(subbed,'r_minus_g')

if __name__ == '__main__':
    cb.addImageCallback(channels)
    cb.start()
