#! /usr/bin/env python2.7

import rospy
import tf
import numpy as np
from std_msgs.msg import Header
from auv_msgs.msg import CVTarget, SetCVTargetAction, SetCVTargetFeedback
from geometry_msgs.msg import Polygon, Point32
import bin_detection
from actionlib import SimpleActionServer
from image_geometry import PinholeCameraModel
from cv_bridge import CvBridge
from sensor_msgs.msg import Image, CameraInfo

bins_depth = 4.7268  # 16 ft - 15 cm
subscribers = []
down_camera_model = None
bridge = CvBridge()


def bins_callback(img):
    if not down_camera_model:
        rospy.logwarn('No camera info')
        return
    rects = bin_detection.findByContours(bridge.imgmsg_to_cv2(img))
    if len(rects) == 0:
        return
    try:
        transform = listener.asMatrix('floating_horizon', img.header)
        # The camera pinhole, in the floating_horizon frame
        perspective_point = np.dot(transform, np.array([0., 0., 0., 1.]))
        perspective_transform = tf.transformations.projection_matrix(
            np.array([0., 0., bins_depth]),
            np.array([0., 0., 1.]),
            perspective=perspective_point)
        target_msg = CVTarget()
        header = Header()
        header.frame_id = 'floating_horizon'
        target_msg.header = header
        target_msg.targets = []
        for rect in rects:
            polygon = Polygon()
            for xy in rect:
                camera_ray = down_camera_model.projectPixelTo3dRay(xy)
                # Convert to homogeneous vector
                camera_ray = [camera_ray[0], camera_ray[1], camera_ray[2], 1.0]
                point = np.dot(perspective_transform,
                               np.dot(transform, camera_ray))
                if point[3] == 0:
                    rospy.logerr('Invalid homogeneous vector')
                    return
                point_msg = Point32()
                point_msg.x = point[0]/point[3]
                point_msg.y = point[1]/point[3]
                point_msg.z = point[2]/point[3]
                polygon.points.append(point_msg)
            target_msg.targets.append(polygon)
        pub.publish(target_msg)
        server.publish_feedback(SetCVTargetFeedback())
    # TODO: Use wait_for_transform?
    except tf.Exception:
        rospy.logerr('Could not get tf between frames {} and {}'
                     .format('floating_horizon', img.header.frame_id))


def camera_info_callback(msg):
    global down_camera_model
    if down_camera_model:
        down_camera_model.fromCameraInfo(msg)
    else:
        down_camera_model = PinholeCameraModel()


def register_target():
    target_name = server.accept_new_goal().target_name
    if target_name == CVTarget.BINS:
        subscribers.append(rospy.Subscriber('camera_down/camera_info',
                                            CameraInfo, camera_info_callback))
        subscribers.append(rospy.Subscriber('camera_down/image_rect_color',
                                            Image, bins_callback))
    else:
        rospy.logerr('Unknown Target')


def cancel_target():
    global subscribers
    [s.unregister() for s in subscribers]
    subscribers = []

target_map = {CVTarget.BINS: bins_callback}

if __name__ == '__main__':
    global listener, pub
    rospy.init_node('cv_server')
    server = SimpleActionServer('cv_server', SetCVTargetAction,
                                auto_start=False)
    server.register_goal_callback(register_target)
    server.register_preempt_callback(cancel_target)
    server.start()
    listener = tf.TransformListener()
    pub = rospy.Publisher('cv/identified_targets', CVTarget, queue_size=100)
    rospy.spin()
