#! /usr/bin/env python2.7

import rospy
from auv_msgs.msg import CVTarget
from geometry_msgs.msg import PolygonStamped


def callback(cv_target):
    msg = PolygonStamped()
    msg.header = cv_target.header
    msg.polygon = cv_target.targets[0]
    pub.publish(msg)


if __name__ == '__main__':
    global pub
    rospy.init_node('reroute_polygons')
    rospy.Subscriber('/cv/identified_targets', CVTarget, callback)
    pub = rospy.Publisher('visualize_polygons', PolygonStamped, queue_size=100)
    rospy.spin()
