#! /usr/bin/env python2.7

import numpy as np
import cv2
import rospy
from sensor_msgs.msg import Image
from cv_bridge import  CvBridge

'''
Author: Max Krogius

Publish a video file as a ros topic

Params:
    ~data - filename of the video file
    ~topic - topic name to publish on
    ~rate - framerate of the video (in hz)
'''

rospy.init_node('video2ros')
pub = rospy.Publisher(rospy.get_param('~topic', 'video2ros/image'), Image, queue_size=10)

try:
    videoFile = rospy.get_param('~data')
except:
    print('Error: No video file specified')
    print('Param name is ~data')
    exit()

cap = cv2.VideoCapture(videoFile)
r = rospy.Rate(rospy.get_param('~rate', cap.get(cv2.cv.CV_CAP_PROP_FPS)))
bridge = CvBridge()

while not rospy.is_shutdown():
    ret, frame = cap.read()
    if not ret:
        break
    pub.publish(bridge.cv2_to_imgmsg(frame, 'bgr8'))
    r.sleep()

# When everything done, release the capture
cap.release()
