/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/dery/Git_Repositories/McGill_RoboSub_2014/catkin_ws/src/simulator/msg/ThrusterForces.msg
 *
 */


#ifndef SIMULATOR_MESSAGE_THRUSTERFORCES_H
#define SIMULATOR_MESSAGE_THRUSTERFORCES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct ThrusterForces_
{
  typedef ThrusterForces_<ContainerAllocator> Type;

  ThrusterForces_()
    : tx1(0.0)
    , tx2(0.0)
    , ty1(0.0)
    , ty2(0.0)
    , tz1(0.0)
    , tz2(0.0)  {
    }
  ThrusterForces_(const ContainerAllocator& _alloc)
    : tx1(0.0)
    , tx2(0.0)
    , ty1(0.0)
    , ty2(0.0)
    , tz1(0.0)
    , tz2(0.0)  {
    }



   typedef float _tx1_type;
  _tx1_type tx1;

   typedef float _tx2_type;
  _tx2_type tx2;

   typedef float _ty1_type;
  _ty1_type ty1;

   typedef float _ty2_type;
  _ty2_type ty2;

   typedef float _tz1_type;
  _tz1_type tz1;

   typedef float _tz2_type;
  _tz2_type tz2;




  typedef boost::shared_ptr< ::simulator::ThrusterForces_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::ThrusterForces_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ThrusterForces_

typedef ::simulator::ThrusterForces_<std::allocator<void> > ThrusterForces;

typedef boost::shared_ptr< ::simulator::ThrusterForces > ThrusterForcesPtr;
typedef boost::shared_ptr< ::simulator::ThrusterForces const> ThrusterForcesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::ThrusterForces_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::ThrusterForces_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'simulator': ['/home/dery/Git_Repositories/McGill_RoboSub_2014/catkin_ws/src/simulator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulator::ThrusterForces_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::ThrusterForces_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::ThrusterForces_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::ThrusterForces_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::ThrusterForces_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::ThrusterForces_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::ThrusterForces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8069d0aad0823ec4cbf5424c4165d4a7";
  }

  static const char* value(const ::simulator::ThrusterForces_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8069d0aad0823ec4ULL;
  static const uint64_t static_value2 = 0xcbf5424c4165d4a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::ThrusterForces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/ThrusterForces";
  }

  static const char* value(const ::simulator::ThrusterForces_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::ThrusterForces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 tx1\n\
float32 tx2\n\
float32 ty1\n\
float32 ty2\n\
float32 tz1\n\
float32 tz2\n\
\n\
";
  }

  static const char* value(const ::simulator::ThrusterForces_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::ThrusterForces_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tx1);
      stream.next(m.tx2);
      stream.next(m.ty1);
      stream.next(m.ty2);
      stream.next(m.tz1);
      stream.next(m.tz2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ThrusterForces_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::ThrusterForces_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::ThrusterForces_<ContainerAllocator>& v)
  {
    s << indent << "tx1: ";
    Printer<float>::stream(s, indent + "  ", v.tx1);
    s << indent << "tx2: ";
    Printer<float>::stream(s, indent + "  ", v.tx2);
    s << indent << "ty1: ";
    Printer<float>::stream(s, indent + "  ", v.ty1);
    s << indent << "ty2: ";
    Printer<float>::stream(s, indent + "  ", v.ty2);
    s << indent << "tz1: ";
    Printer<float>::stream(s, indent + "  ", v.tz1);
    s << indent << "tz2: ";
    Printer<float>::stream(s, indent + "  ", v.tz2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_THRUSTERFORCES_H
