#!/usr/bin/env python

import rospy
from std_msgs.msg import Float32, Float64


def callback(msg):
    pub.publish(msg.data * 10.1974428892 / 1000 - 10.1974428892)


if __name__ == "__main__":
    rospy.init_node("depth")
    pub = rospy.Publisher("/state_estimation/depth", Float64, queue_size=10)
    rospy.Subscriber("/electrical_interface/pressure", Float32, callback)
    rospy.spin()
