#! /usr/bin/env python2.7
'''
Author: Max Krogius

Quick prototyping of CV filters. Create a filter in the filters folder
and use this to quickly test it on either a ros topic, a video, or an image.
It can either display the image or publish it as a ros topic.
be specified.

Subscriptions:
    /image [sensor_msgs/Image] : For the input image

Publications:
    /quick_test/image [sensor_msgs/Image] : Output image

Params:
    ~filter : Name of filter to apply. If not provided, will pass image through
        without filtering.
'''

import rospy
import filters
from sensor_msgs.msg import Image
from cv_bridge import CvBridge

rospy.init_node('quick_test')
filter_name = rospy.get_param('~filter', 'passthrough')
filter_func = getattr(filters, filter_name).filter

pub = rospy.Publisher('quick_test/image', Image, queue_size=10)
bridge = CvBridge()
rospy.Subscriber('image', Image, 
        lambda img: pub.publish(bridge.cv2_to_imgmsg(filter_func(bridge.imgmsg_to_cv2(img)), 'bgr8')))
rospy.spin()

