#! /usr/bin/env python2.7
import rospy
from geometry_msgs.msg import Wrench
from auv_msgs.msg import RadioCommands

rc_center = 1500


def rc_callback(msg):
    wrench = Wrench()
    wrench.force.x = (msg.channel1 - rc_center) / 500
    wrench.force.y = (msg.channel2 - rc_center) / 500
    wrench.force.z = (msg.channel3 - rc_center) / 500
    wrench.torque.z = (msg.channel4 - rc_center) / 500
    pub.publish(wrench)


if __name__ == '__main__':
    global pub, sub
    rospy.init_node('remote_control')
    pub = rospy.Publisher('controls/wrench', Wrench, queue_size=10)
    sub = rospy.Subscriber('radio', RadioCommands, rc_callback)
    rospy.spin()
