/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/vivi/auv/catkin_ws/src/auv_msgs/msg/CVTarget.msg
 *
 */


#ifndef AUV_MSGS_MESSAGE_CVTARGET_H
#define AUV_MSGS_MESSAGE_CVTARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auv_msgs
{
template <class ContainerAllocator>
struct CVTarget_
{
  typedef CVTarget_<ContainerAllocator> Type;

  CVTarget_()
    : CVTarget(0)  {
    }
  CVTarget_(const ContainerAllocator& _alloc)
    : CVTarget(0)  {
    }



   typedef uint8_t _CVTarget_type;
  _CVTarget_type CVTarget;


    enum { NOTHING = 0u };
     enum { GATE = 1u };
     enum { BUOY = 2u };
     enum { LANE = 3u };
 

  typedef boost::shared_ptr< ::auv_msgs::CVTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auv_msgs::CVTarget_<ContainerAllocator> const> ConstPtr;

}; // struct CVTarget_

typedef ::auv_msgs::CVTarget_<std::allocator<void> > CVTarget;

typedef boost::shared_ptr< ::auv_msgs::CVTarget > CVTargetPtr;
typedef boost::shared_ptr< ::auv_msgs::CVTarget const> CVTargetConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auv_msgs::CVTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auv_msgs::CVTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'auv_msgs': ['/home/vivi/auv/catkin_ws/src/auv_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auv_msgs::CVTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_msgs::CVTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_msgs::CVTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_msgs::CVTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_msgs::CVTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_msgs::CVTarget_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auv_msgs::CVTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1bcd46034f8c9e5490893c5a24fa63fd";
  }

  static const char* value(const ::auv_msgs::CVTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1bcd46034f8c9e54ULL;
  static const uint64_t static_value2 = 0x90893c5a24fa63fdULL;
};

template<class ContainerAllocator>
struct DataType< ::auv_msgs::CVTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auv_msgs/CVTarget";
  }

  static const char* value(const ::auv_msgs::CVTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auv_msgs::CVTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 CVTarget\n\
\n\
uint8 NOTHING=0\n\
uint8 GATE=1\n\
uint8 BUOY=2\n\
uint8 LANE=3\n\
";
  }

  static const char* value(const ::auv_msgs::CVTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auv_msgs::CVTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.CVTarget);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CVTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auv_msgs::CVTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auv_msgs::CVTarget_<ContainerAllocator>& v)
  {
    s << indent << "CVTarget: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.CVTarget);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUV_MSGS_MESSAGE_CVTARGET_H
