/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/vivi/auv/catkin_ws/src/auv_msgs/msg/Motor.msg
 *
 */


#ifndef AUV_MSGS_MESSAGE_MOTOR_H
#define AUV_MSGS_MESSAGE_MOTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auv_msgs
{
template <class ContainerAllocator>
struct Motor_
{
  typedef Motor_<ContainerAllocator> Type;

  Motor_()
    : Motor1(0)
    , Motor2(0)
    , Motor3(0)
    , Motor4(0)
    , Motor5(0)
    , Motor6(0)
    , Motor7(0)
    , Motor8(0)  {
    }
  Motor_(const ContainerAllocator& _alloc)
    : Motor1(0)
    , Motor2(0)
    , Motor3(0)
    , Motor4(0)
    , Motor5(0)
    , Motor6(0)
    , Motor7(0)
    , Motor8(0)  {
    }



   typedef int16_t _Motor1_type;
  _Motor1_type Motor1;

   typedef int16_t _Motor2_type;
  _Motor2_type Motor2;

   typedef int16_t _Motor3_type;
  _Motor3_type Motor3;

   typedef int16_t _Motor4_type;
  _Motor4_type Motor4;

   typedef int16_t _Motor5_type;
  _Motor5_type Motor5;

   typedef int16_t _Motor6_type;
  _Motor6_type Motor6;

   typedef int16_t _Motor7_type;
  _Motor7_type Motor7;

   typedef int16_t _Motor8_type;
  _Motor8_type Motor8;




  typedef boost::shared_ptr< ::auv_msgs::Motor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auv_msgs::Motor_<ContainerAllocator> const> ConstPtr;

}; // struct Motor_

typedef ::auv_msgs::Motor_<std::allocator<void> > Motor;

typedef boost::shared_ptr< ::auv_msgs::Motor > MotorPtr;
typedef boost::shared_ptr< ::auv_msgs::Motor const> MotorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auv_msgs::Motor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auv_msgs::Motor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'auv_msgs': ['/home/vivi/auv/catkin_ws/src/auv_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auv_msgs::Motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_msgs::Motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_msgs::Motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_msgs::Motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_msgs::Motor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_msgs::Motor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auv_msgs::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ede24e8c7884b1a6238f81f9f1c05866";
  }

  static const char* value(const ::auv_msgs::Motor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xede24e8c7884b1a6ULL;
  static const uint64_t static_value2 = 0x238f81f9f1c05866ULL;
};

template<class ContainerAllocator>
struct DataType< ::auv_msgs::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auv_msgs/Motor";
  }

  static const char* value(const ::auv_msgs::Motor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auv_msgs::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 Motor1\n\
int16 Motor2\n\
int16 Motor3\n\
int16 Motor4\n\
int16 Motor5\n\
int16 Motor6\n\
int16 Motor7\n\
int16 Motor8\n\
";
  }

  static const char* value(const ::auv_msgs::Motor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auv_msgs::Motor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Motor1);
      stream.next(m.Motor2);
      stream.next(m.Motor3);
      stream.next(m.Motor4);
      stream.next(m.Motor5);
      stream.next(m.Motor6);
      stream.next(m.Motor7);
      stream.next(m.Motor8);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Motor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auv_msgs::Motor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auv_msgs::Motor_<ContainerAllocator>& v)
  {
    s << indent << "Motor1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Motor1);
    s << indent << "Motor2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Motor2);
    s << indent << "Motor3: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Motor3);
    s << indent << "Motor4: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Motor4);
    s << indent << "Motor5: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Motor5);
    s << indent << "Motor6: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Motor6);
    s << indent << "Motor7: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Motor7);
    s << indent << "Motor8: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Motor8);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUV_MSGS_MESSAGE_MOTOR_H
