/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/vivi/auv/catkin_ws/src/auv_msgs/msg/SetVelocity.msg
 *
 */


#ifndef AUV_MSGS_MESSAGE_SETVELOCITY_H
#define AUV_MSGS_MESSAGE_SETVELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auv_msgs
{
template <class ContainerAllocator>
struct SetVelocity_
{
  typedef SetVelocity_<ContainerAllocator> Type;

  SetVelocity_()
    : surgeSpeed(0.0)
    , swaySpeed(0.0)
    , depth(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  SetVelocity_(const ContainerAllocator& _alloc)
    : surgeSpeed(0.0)
    , swaySpeed(0.0)
    , depth(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }



   typedef double _surgeSpeed_type;
  _surgeSpeed_type surgeSpeed;

   typedef double _swaySpeed_type;
  _swaySpeed_type swaySpeed;

   typedef double _depth_type;
  _depth_type depth;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;




  typedef boost::shared_ptr< ::auv_msgs::SetVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auv_msgs::SetVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct SetVelocity_

typedef ::auv_msgs::SetVelocity_<std::allocator<void> > SetVelocity;

typedef boost::shared_ptr< ::auv_msgs::SetVelocity > SetVelocityPtr;
typedef boost::shared_ptr< ::auv_msgs::SetVelocity const> SetVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auv_msgs::SetVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auv_msgs::SetVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'auv_msgs': ['/home/vivi/auv/catkin_ws/src/auv_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auv_msgs::SetVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_msgs::SetVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_msgs::SetVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_msgs::SetVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_msgs::SetVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_msgs::SetVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auv_msgs::SetVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7264863be4ad78ee2279c4f191ebbd50";
  }

  static const char* value(const ::auv_msgs::SetVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7264863be4ad78eeULL;
  static const uint64_t static_value2 = 0x2279c4f191ebbd50ULL;
};

template<class ContainerAllocator>
struct DataType< ::auv_msgs::SetVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auv_msgs/SetVelocity";
  }

  static const char* value(const ::auv_msgs::SetVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auv_msgs::SetVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 surgeSpeed\n\
float64 swaySpeed\n\
float64 depth\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
";
  }

  static const char* value(const ::auv_msgs::SetVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auv_msgs::SetVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.surgeSpeed);
      stream.next(m.swaySpeed);
      stream.next(m.depth);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auv_msgs::SetVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auv_msgs::SetVelocity_<ContainerAllocator>& v)
  {
    s << indent << "surgeSpeed: ";
    Printer<double>::stream(s, indent + "  ", v.surgeSpeed);
    s << indent << "swaySpeed: ";
    Printer<double>::stream(s, indent + "  ", v.swaySpeed);
    s << indent << "depth: ";
    Printer<double>::stream(s, indent + "  ", v.depth);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUV_MSGS_MESSAGE_SETVELOCITY_H
