/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/vivi/auv/catkin_ws/src/auv_msgs/msg/Solenoid.msg
 *
 */


#ifndef AUV_MSGS_MESSAGE_SOLENOID_H
#define AUV_MSGS_MESSAGE_SOLENOID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auv_msgs
{
template <class ContainerAllocator>
struct Solenoid_
{
  typedef Solenoid_<ContainerAllocator> Type;

  Solenoid_()
    : solenoid1(false)
    , solenoid2(false)
    , solenoid3(false)
    , solenoid4(false)
    , solenoid5(false)
    , solenoid6(false)  {
    }
  Solenoid_(const ContainerAllocator& _alloc)
    : solenoid1(false)
    , solenoid2(false)
    , solenoid3(false)
    , solenoid4(false)
    , solenoid5(false)
    , solenoid6(false)  {
    }



   typedef uint8_t _solenoid1_type;
  _solenoid1_type solenoid1;

   typedef uint8_t _solenoid2_type;
  _solenoid2_type solenoid2;

   typedef uint8_t _solenoid3_type;
  _solenoid3_type solenoid3;

   typedef uint8_t _solenoid4_type;
  _solenoid4_type solenoid4;

   typedef uint8_t _solenoid5_type;
  _solenoid5_type solenoid5;

   typedef uint8_t _solenoid6_type;
  _solenoid6_type solenoid6;




  typedef boost::shared_ptr< ::auv_msgs::Solenoid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auv_msgs::Solenoid_<ContainerAllocator> const> ConstPtr;

}; // struct Solenoid_

typedef ::auv_msgs::Solenoid_<std::allocator<void> > Solenoid;

typedef boost::shared_ptr< ::auv_msgs::Solenoid > SolenoidPtr;
typedef boost::shared_ptr< ::auv_msgs::Solenoid const> SolenoidConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auv_msgs::Solenoid_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auv_msgs::Solenoid_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auv_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'auv_msgs': ['/home/vivi/auv/catkin_ws/src/auv_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auv_msgs::Solenoid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_msgs::Solenoid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_msgs::Solenoid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_msgs::Solenoid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_msgs::Solenoid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_msgs::Solenoid_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auv_msgs::Solenoid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0efcb9185f05bca53eb2775d2b56d3f1";
  }

  static const char* value(const ::auv_msgs::Solenoid_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0efcb9185f05bca5ULL;
  static const uint64_t static_value2 = 0x3eb2775d2b56d3f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::auv_msgs::Solenoid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auv_msgs/Solenoid";
  }

  static const char* value(const ::auv_msgs::Solenoid_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auv_msgs::Solenoid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool solenoid1\n\
bool solenoid2\n\
bool solenoid3\n\
bool solenoid4\n\
bool solenoid5\n\
bool solenoid6\n\
";
  }

  static const char* value(const ::auv_msgs::Solenoid_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auv_msgs::Solenoid_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.solenoid1);
      stream.next(m.solenoid2);
      stream.next(m.solenoid3);
      stream.next(m.solenoid4);
      stream.next(m.solenoid5);
      stream.next(m.solenoid6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Solenoid_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auv_msgs::Solenoid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auv_msgs::Solenoid_<ContainerAllocator>& v)
  {
    s << indent << "solenoid1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.solenoid1);
    s << indent << "solenoid2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.solenoid2);
    s << indent << "solenoid3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.solenoid3);
    s << indent << "solenoid4: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.solenoid4);
    s << indent << "solenoid5: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.solenoid5);
    s << indent << "solenoid6: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.solenoid6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUV_MSGS_MESSAGE_SOLENOID_H
